// var temp = 98.6;
// var beanCounter = 4;
// var reallyCool = true;
// var motto = "I Rule";
// temp = (temp - 32) * 5 / 9;
// motto = motto + " and so do you!"; var pos = Math.random();
// while (beanCounter > 0) { processBeans();
//     beanCounter = beanCounter - 1; }
//     if (isReallyCool) {
//         invite = "You're invited!";
//         3
//         } else {
//         invite = "Sorry, we're at capacity."; }
